kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local
commonLabels: {}
commonAnnotations: {}

slurmctld:
  image:
    registry: docker-registry.lab.zverse.space
    repository: data-and-computing/slurm-slurmctld
    tag: "25.05"
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 1
  resources: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []
  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: false
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  service:
    type: ClusterIP
    name: slurmctld
    port: 6817
    targetPort: 6817
  persistence:
    enabled: true
    mountPath: /var/spool/slurmctld
    annotations: {}
    accessModes:
      - ReadWriteMany
    size: 10Gi
    storageClass: "juicefs-tidb-oss-01"
    existingClaim: ""
slurmdbd:
  image:
    registry: docker-registry.lab.zverse.space
    repository: data-and-computing/slurm-slurmdbd
    tag: "25.05"
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 1
  resources: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []
  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: false
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  service:
    type: ClusterIP
    name: slurmdbd
    port: 6819
    targetPort: 6819
slurmd:
  image:
    registry: docker-registry.lab.zverse.space
    repository: data-and-computing/slurm-slurmd
    tag: "intelmpi-250208-r0-lensing-v5.3"
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 3
  affinity: {}
  nodeSelector: {}
  tolerations: []
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: false
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  service:
    type: ClusterIP
    port: 6819
    name: slurmd
    targetPort: 6819
slurmcli:
  image:
    registry: docker-registry.lab.zverse.space
    repository: data-and-computing/slurm-login
    tag: "intelmpi-250208-r0-lensing-v4"
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 1
  resources: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []
  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: false
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  service:
    type: ClusterIP
    port: 22
    name: slurmcli
    targetPort: 22
munged:
  image:
    registry: docker-registry.lab.zverse.space
    repository: data-and-computing/slurm-munged
    tag: "25.05"
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
  extraEnv: []
  extraVolumes: []
  extraVolumeMounts: []
mariadb:
  global:
    security:
      allowInsecureImages: true
  image:
    registry: m.daocloud.io/docker.io
  auth:
    rootPassword: "restricted"
    database: slurm-cluster
    username: "slurm"
    password: "slurm"
    existingSecret: ""
  primary:
    persistence:
      storageClass: "juicefs-tidb-oss-01"

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

persistence:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteMany
  size: 10Gi
  storageClass: "juicefs-tidb-oss-01"
  existingClaim: ""
