
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurm.fullname" . }}-cgroup-conf
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  cgroup.conf: |-
    CgroupPlugin=autodetect
    IgnoreSystemd=yes
    IgnoreSystemdOnFailure=yes
    ConstrainCores=yes
    ConstrainDevices=yes
    ConstrainRAMSpace=yes
    ConstrainSwapSpace=no
