apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurm.fullname" . }}-slurmdbd-conf
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.slurmdbd.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.slurmdbd.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdbd.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  slurmdbd.conf: |-
    AuthType=auth/munge
    AuthInfo=/var/run/munge/munge.socket.2
    SlurmUser=slurm
    DebugLevel=verbose
    LogFile=/var/log/slurm/slurmdbd.log
    PidFile=/var/run/slurmdbd.pid
    DbdHost={{ include "slurm.fullname" . }}-slurmdbd
    DbdPort={{ .Values.slurmdbd.service.port }}
    StorageType=accounting_storage/mysql
    StorageHost={{ .Release.Name }}-mariadb
    StoragePort={{ .Values.mariadb.primary.service.ports.mysql }}
    StoragePass={{ .Values.mariadb.auth.rootPassword }}
    StorageUser=root
    StorageLoc={{ .Values.mariadb.auth.database }}
