apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-slurmdbd
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.slurmdbd.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.slurmdbd.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdbd.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.slurmdbd.replicaCount }}
  revisionHistoryLimit: {{ .Values.slurmdbd.revisionHistoryLimit }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.slurmdbd.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: slurmdbd
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: slurmdbd
      annotations:
        kubectl.kubernetes.io/default-container: slurmdbd
        {{- if .Values.slurmdbd.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdbd.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      hostname: {{ include "common.names.fullname" . }}-slurmdbd
      automountServiceAccountToken: false
      containers:
      - image: "{{ .Values.munged.image.registry }}/{{ .Values.munged.image.repository }}:{{ .Values.munged.image.tag }}"
        imagePullPolicy: {{ .Values.munged.image.pullPolicy }}
        name: munged
        {{- if .Values.munged.resources }}
        resources: {{- toYaml .Values.munged.resources | nindent 12 }}
        {{- end }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/munge
          name: munge-socket-file
      - image: "{{ .Values.slurmdbd.image.registry }}/{{ .Values.slurmdbd.image.repository }}:{{ .Values.slurmdbd.image.tag }}"
        imagePullPolicy: {{ .Values.slurmdbd.image.pullPolicy }}
        name: slurmdbd
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        - containerPort: 6819
          name: slurmdbd
          protocol: TCP
        {{- if .Values.slurmctld.resources }}
        resources: {{- toYaml .Values.slurmctld.resources | nindent 12 }}
        {{- end }}
        securityContext:
          privileged: true
        volumeMounts:
        # - mountPath: /root/.ssh
        #   name: ssh-keys
        #   readOnly: true
        - mountPath: /opt/slurm/slurmdbd.conf
          name: slurmdbd-conf-file
          subPath: slurmdbd.conf
        # - mountPath: /etc/slurm/cgroup.conf
        #   name: cgroup-conf-file
        #   subPath: cgroup.conf
        - mountPath: /run/munge
          name: munge-socket-file
      initContainers:
      - command:
        - sh
        - -c
        - chmod 755 /run/munge && chown 1108:1108 /run/munge
        image: m.daocloud.io/docker.io/library/busybox:1.37.0-glibc
        imagePullPolicy: IfNotPresent
        name: init-permission
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/munge
          name: munge-socket-file
      - name: wait-for-mariadb
        image: m.daocloud.io/docker.io/library/busybox:1.37.0-glibc
        command:
          - sh
          - -c
          - |
            until nc -z {{ .Release.Name }}-mariadb {{ .Values.mariadb.primary.service.ports.mysql }}; do
              echo "waiting for mariadb...";
              sleep 3;
            done
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: Always
      serviceAccount: {{ include "slurm.serviceAccountName" . }}
      serviceAccountName: {{ include "slurm.serviceAccountName" . }}
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ssh-keys
        # secret:
        #   defaultMode: 420
        #   items:
        #   - key: id_rsa
        #     mode: 256
        #     path: id_rsa
        #   - key: id_rsa.pub
        #     mode: 444
        #     path: id_rsa.pub
        #   - key: authorized_keys
        #     mode: 384
        #     path: authorized_keys
        #   secretName: slurm-ssh-keys
      - configMap:
          defaultMode: 420
          name: {{ include "common.names.fullname" . }}-slurmdbd-conf
        name: slurmdbd-conf-file
      # - configMap:
      #     defaultMode: 420
      #     name: slurm-lensing-slurm-cgroup-conf
        # name: cgroup-conf-file
      - emptyDir: {}
        name: munge-socket-file
