
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurm.fullname" . }}-slurm-conf
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  slurm.conf: |-
    DebugFlags=cgroup
    SlurmdDebug=debug
    ClusterName={{ include "slurm.fullname" . }}
    {{- if eq .Values.slurmctld.replicaCount 1 }}
    SlurmctldHost={{ include "slurm.fullname" . }}-slurmctld-0
    {{- else if eq .Values.slurmctld.replicaCount 3 }}
    SlurmctldHost={{ include "slurm.fullname" . }}-slurmctld-0
    SlurmctldHost={{ include "slurm.fullname" . }}-slurmctld-1
    SlurmctldHost={{ include "slurm.fullname" . }}-slurmctld-2
    {{- end }}
    MpiDefault=pmi2
    ReturnToService=1
    SlurmctldPidFile=/var/run/slurmctld.pid
    SlurmctldPort={{ .Values.slurmctld.service.port }}
    SlurmdPidFile=/var/run/slurmd.pid
    SlurmdPort={{ .Values.slurmd.service.port }}
    SlurmdSpoolDir=/var/spool/slurmd
    SlurmUser=slurm
    StateSaveLocation=/var/spool/slurmctld
    TaskPlugin=task/affinity,task/cgroup
    ProctrackType=proctrack/cgroup
    InactiveLimit=0
    KillWait=30
    MinJobAge=300
    SlurmctldTimeout=120
    SlurmdTimeout=300
    Waittime=0
    SchedulerType=sched/backfill
    SelectType=select/cons_tres
    AccountingStorageHost={{ include "slurm.fullname" . }}-slurmdbd
    AccountingStoragePort={{ .Values.slurmdbd.service.port }}
    AccountingStorageType=accounting_storage/slurmdbd
    AccountingStoreFlags=job_comment
    JobAcctGatherType=jobacct_gather/linux
    JobAcctGatherFrequency=30
    SlurmctldDebug=info
    SlurmctldLogFile=/var/log/slurm/slurmctld.log
    SlurmdLogFile=/var/log/slurm/slurmd.log

    Nodeset=cnconti Feature=cnconti-node
    PartitionName=dyn Nodes=cnconti Default=yes
