apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-ssh-keygen
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-timeout: "10m"
spec:
  ttlSecondsAfterFinished: 1800
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: {{ include "slurm.serviceAccountName" . }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      initContainers:
      - name: generate-key-pair
        {{- if and .Values.image.mirror.registry (ne .Values.image.mirror.registry "") }}
        image: {{ .Values.image.mirror.registry }}/docker.io/library/alpine:3.19
        {{- else }}
        image: m.daocloud.io/docker.io/library/alpine:3.19
        {{- end }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "nameserver 8.8.8.8" >> /etc/resolv.conf &&
            echo "nameserver 114.114.114.114" >> /etc/resolv.conf &&
            apk add --no-cache openssh-client &&
            ssh-keygen -t rsa -b 4096 -N '' -f /keys/id_rsa &&
            cp /keys/id_rsa.pub /keys/authorized_keys
            {{- range .Values.auth.ssh.configmap.prefabPubKeys }}
                echo {{ . }} >> /keys/authorized_keys
            {{- end }}
        volumeMounts:
        - name: keys
          mountPath: /keys
      containers:
      - name: create-secret
        {{- if and .Values.image.mirror.registry (ne .Values.image.mirror.registry "") }}
        image: {{ .Values.image.mirror.registry }}/docker.io/bitnami/kubectl:1.28-debian-11
        {{- else }}
        image: m.daocloud.io/docker.io/bitnami/kubectl:1.28-debian-11
        {{- end }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            if kubectl -n {{ .Release.Namespace }} get secret {{ .Values.auth.ssh.secret.name }}; then
              echo "SSH keys already exist. Skipping key generation.";
            else
              kubectl -n {{ .Release.Namespace }} create secret generic {{ .Values.auth.ssh.secret.name }} \
              --from-file=id_rsa=/keys/id_rsa \
              --from-file=id_rsa.pub=/keys/id_rsa.pub \
              --from-file=authorized_keys=/keys/id_rsa.pub
            fi
            if kubectl -n {{ .Release.Namespace }} get configmap {{ .Values.auth.ssh.configmap.name }}; then
              echo "SSH preset pub configmap already exist. Skipping configmap creation.";
            else
              kubectl -n {{ .Release.Namespace }} create configmap {{ .Values.auth.ssh.configmap.name }} \
                --from-file=authorized_keys=/keys/authorized_keys
            fi
        volumeMounts:
        - name: keys
          mountPath: /keys
      restartPolicy: OnFailure
      volumes:
      - name: keys
        emptyDir: {}
